### ISSUE TITLE
Is this plugin still needed?

### ISSUE THREAD

**Issue by jakub-bochenski** [outbrain-inc/ci-friendly-flatten-maven-plugin#65]
Why would I need this plugin if https://github.com/mojohaus/flatten-maven-plugin/issues/103 is marked as fixed?

**Comment by ayoukhananov** [comment]
Hey @jakub-bochenski 
The ci-friendly-flatten-maven-plugin was designed to address a specific problem in a simple and reliable way: enabling CI-friendly POM flattening for Maven builds.

While mojohaus/flatten-maven-plugin is a feature-rich plugin, it does many things beyond solving this problem. Its broader scope and complexity have historically led to issues and inconsistencies, as seen in #103 and other past challenges.
